name: Build and Deploy Doxygen Docs

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen + Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen Docs
        run: doxygen Doxyfile

      - name: Prevent Jekyll
        run: touch docs/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/html
          github_token: ${{ secrets.TEST }}   # or GH_PAT if needed
          publish_branch: gh-pages
          force_orphan: true